---
name: Haskell CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        plan:
          - build: stack

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: TeX-Live/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            forest
            preview
            dvisvgm

      - name: Restore Stack
        id: cache-stack-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}
            ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-

      - name: Restore .stack-work
        id: cache-stack-work-restore
        uses: actions/cache/restore@v4
        with:
          path: .stack-work
          key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.plan.build }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
            ${{ matrix.os }}-${{ matrix.plan.build }}-stack-work-${{ hashFiles('stack.yaml') }}
            ${{ matrix.os }}-${{ matrix.plan.build }}-stack-work-

      - name: Setup stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install dependencies
        run: |
          set -ex
          stack --no-terminal --install-ghc test --bench --only-dependencies
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}

      - name: Build and test
        run: |
          set -ex
          stack --no-terminal test --coverage --bench --no-run-benchmarks --haddock --no-haddock-deps
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}

      - name: Cache Stack
        id: cache-stack-save
        uses: actions/cache/save@v4
        with:
          path: ~/.stack
          key: ${{ steps.cache-stack-restore.outputs.cache-primary-key }}
        if: >-
          steps.cache-stack-restore.outputs.cache-hit != 'true'

      - name: Cache .stack-work
        id: cache-stack-work-save
        uses: actions/cache/save@v4
        with:
          path: .stack-work
          key: ${{ steps.cache-stack-work-restore.outputs.cache-primary-key }}
        if: >-
          steps.cache-stack-work-restore.outputs.cache-hit != 'true'

      - name: Escape commit message
        id: escape
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "commit_msg=$(echo "$COMMIT_MSG" | jq -Rs '.|rtrimstr("\n")')" >> "$GITHUB_OUTPUT"

      - name: Trigger Test-Flex
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: CI-Completed
          client-payload: '{"sha": "${{ github.sha }}", "message": ${{ steps.escape.outputs.commit_msg }}}'
