---
name: Compile and Lint Flex-Tasks

on:
  repository_dispatch:
    types: [CI-Completed]

permissions:
  contents: write

jobs:
  test_flex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fmidue/flex-tasks/.github/actions/test-flex@main
        with:
          tasks: src
          config: .github/actions/test-flex
          settings-gens: src/settings-gens
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

